Final_capstone/data_science_meetup_blog/blog_posts/forms.py
# blog_post/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('BlogPost')

Final_capstone/data_science_meetup_blog/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from data_science_meetup_blog import db
from data_science_meetup_blog.models import BlogPost
from data_science_meetup_blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )
 
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

Final_capstone/data_science_meetup_blog/core/views.py
from flask import Blueprint, render_template, request
from data_science_meetup_blog.models import BlogPost

core = Blueprint('core', __name__)

DEFAULT_PAGE = 1
POSTS_PER_PAGE = 10

@core.route('/')
def index():
    page = request.args.get('page', DEFAULT_PAGE, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=POSTS_PER_PAGE)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

Final_capstone/data_science_meetup_blog/users/views.py
from data_science_meetup_blog import db
from data_science_meetup_blog.models import BlogPost, User
from data_science_meetup_blog.users.forms import (LoginForm, RegistrationForm, UpdateUserForm)
from data_science_meetup_blog.users.picture_handler import add_profile_pic
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

users = Blueprint('users', __name__)

FLASH_MESSAGES = {
    'register_success': 'Thanks for registration!',
    'login_success': 'Log in Success!',
    'update_success': 'User Account Updated'
}


def flash_and_redirect(message_key, redirect_url):
    flash(FLASH_MESSAGES.get(message_key))
    return redirect(redirect_url)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return flash_and_redirect('register_success', url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            next_url = request.args.get('next') or url_for('core.index')
            return redirect(next_url)
    return render_template('login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            pic = add_profile_pic(form.picture.data, current_user.username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        return flash_and_redirect('update_success', url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

Final_capstone/data_science_meetup_blog/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    </div>
  </div>

  <div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>
    
      <div class="form-group">
      {{form.email.label(class='form-group')}}
      {{form.email(class='form-control')}}
      </div>

      <div class="form-group">
      {{form.picture.label(class='form-group')}}
      {{form.picture(class='form-control')}}
      </div>

      <div class="form-group">
       {{form.submit(class='btn btn-primary')}}
      </div>


    </form>
  </div>

{% endblock %}

Final_capstone/data_science_meetup_blog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300;400&family=Poppins:ital,wght@1,700&display=swap"
    rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <meta charset="utf-8">
  <title>Hacker's Hideout</title>
  <style>
    body {

      background-color: rgb(255, 255, 255);
      color: rgb(0, 0, 0);
      margin: 0;
      padding: 0;
    }

    .advertisement {
      display: flex;
      justify-content: center;
      background-color: rgb(0, 0, 0);
      color: rgb(255, 255, 255);
      padding: 10px;

    }

    .nav {
      display: flex;
      justify-content: space-between;
      background-color: rgb(255, 255, 255);
      border-bottom: 1px solid black;
    }

    .nav-link {
      list-style: none;
      display: inline;
    }

    .nav-link-top {
      list-style: none;
      display: inline;
      font-family: 'Dosis', sans-serif;

    }

    .nav-link a {
      color: rgb(0, 0, 0);
      text-decoration: none;
      padding: 5px 10px;
      font-family: 'Dosis', sans-serif;

    }

    .nav-link-top a {
      color: rgb(0, 255, 26);
      text-decoration: none;
      padding: 5px 10px;
      font-family: 'Dosis', sans-serif;

    }

    .nav-link a:hover {
      background-color: white;
      color: black;
    }

    .jumbotron {
      margin-top: 50px;
      background-color: white;
      color: black;
    }

    .btn {
      background-color: white;
      color: black;
      border-radius: 0;
      border: 1px solid black;
      font-family: 'Dosis', sans-serif;


    }

    .cta {
      background-color: rgb(0, 255, 26);
      color: rgb(0, 0, 0);
      border-radius: 0;
      border: 1px solid black;
      font-family: 'Dosis', sans-serif;

    }
    .card-title {
      color: black;
      font-family: 'Dosis', sans-serif;
    }
    .card-text {
      color: black;
      font-family: 'Dosis', sans-serif;
      font-size: 16px;
    }


    h1,
    p {
      font-family: 'Dosis', sans-serif;
      font-weight: 200;
    }

    .btn-primary {

      background-color: rgb(0, 0, 0);
      color: rgb(255, 255, 255);
    }

    .btn-primary:hover {
      background-color: rgb(0, 255, 26);
      color: rgb(0, 0, 0);

    }
    
  </style>
</head>

<body>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <ul class="advertisement">
        <li class="nav-link-top">We've just launched a new feature!
          <a href="{{ url_for('core.index') }}">Check out the new dashboard!</a>
        </li>
      </ul>
    </li>
  </ul>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">HH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('core.info') }}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Create Post</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </nav>

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>


</body>

</html>

Final_capstone/data_science_meetup_blog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2 class="card-text">Written by: {{post.author.username}}</h2>
  <h3 class="card-text">Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>

  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

Final_capstone/data_science_meetup_blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <form class="form-group" method="POST">
      {{ form.hidden_tag() }}

      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {{ form.title(class="form-control form-control-lg", style="color: black") }}
      </div>
      <div class="form-group">
        {{ form.text.label(class="form-control-label") }}
        {{ form.text(class="form-control form-control-lg", style="color: black") }}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock %}

Final_capstone/data_science_meetup_blog/templates/index.html
{% extends "base.html" %}
{% block content %}
<br><br>
<div class="jumbotron">
  <h1 class="display-4">Hacker's Hideout｜Where Ideas Thrive </h1>
  <p class="lead">「ハッカーの隠れ家」への参加を歓迎します。
    この場所は、創造的なアイデアに興味を持つ方々を対象とした秘密の場所です。</p>
  <p class="lead">
  </p>
  <hr class="my-4">
  <p>
    今回のイベントでは、エンジニアリング、デザイン、革新的なアイデアに関連するさまざまなトピックを探求します。初心者であろうと経験豊富なプロフェッショナルであろうと、このイベントは人脈を広げ、専門家から学び、知識を他人と共有する絶好の機会を提供します。
  </p>

  <p>
    洞察力のある講演、インタラクティブなワークショップ、魅力的なディスカッションに参加しましょう。アイデアが蓄積する場所で、他の開発者と共に集まりましょう。この刺激的なイベントを見逃さないでください！今すぐ参加登録を行い、場所を確保しましょう。
  </p>
  <br>
  <a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">今すぐ登録</a>
  <a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button"
    style="    background-color: rgb(0, 255, 26); color: black;">Register Now</a>
</div>
 

<br><br><br><br><br><br>
<div class="container">
  {# Go through each blog post #}
  {% for post in blog_posts.items %}
  <div class="card">
    <div class="card-body" style="color: black;">
      <h2><a class="card-title" href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
      <a class="card-text" href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
      <p class="card-text">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
      <p class="card-text" style="color: black;">{{ post.text[:100] }}...</p>
      <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
    </div>
  </div>
  <br>
  {% endfor %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if blog_posts.page == page_num %}
      <li class="page-item disabled">
        <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
      </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </nav>
</div>
{% endblock %}

Final_capstone/data_science_meetup_blog/templates/info.html
{% extends "base.html" %}

{% block content %}
   <div class="jumbotron">
    <h1 class="display-4">Welcome to the Hacker's Hideout</h1>
    <hr class="my-4">
    <p class="lead">This is a simple blog application built with Flask &#x1F4BB;</p>
    <p>Here you can find a community of data science enthusiasts sharing their knowledge, experiences, and insights. Whether you are a beginner or an expert in data science, this blog is the perfect platform to learn, engage, and connect with like-minded individuals.&#x1F389;</p>
    <p>Our mission is to provide a space for data scientists, analysts, and enthusiasts to collaborate, share ideas, and stay updated with the latest trends and advancements in the field of data science &#x1F4DA;</p>
    <p>Explore the blog posts, interact with the authors, and join the discussions &#x1F4AC;. We encourage you to contribute your own blog posts and become a part of our growing community &#x1F64C;</p>
    <p>Join us today and embark on a journey of learning, exploration, and growth in the exciting world of data science &#x1F680;</p>
   </div>
{% endblock %}

Final_capstone/data_science_meetup_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form method="POST" class="mt-4">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label(class="form-label") }}
      {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-label") }}
      {{ form.password(class="form-control") }}
    </div>
    {{ form.submit(class="btn btn-primary mt-3") }}
  </form>
{% endblock %}

Final_capstone/data_science_meetup_blog/templates/register.html
{% extends "base.html" %}
{% block content %}
  <form method="POST" class="mt-4">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label(class="form-label") }}
      {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.username.label(class="form-label") }}
      {{ form.username(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-label") }}
      {{ form.password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.pass_confirm.label(class="form-label") }}
      {{ form.pass_confirm(class="form-control") }}
    </div>
    {{ form.submit(class="btn btn-primary mt-3") }}
  </form>
{% endblock %}

Final_capstone/data_science_meetup_blog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}